
--  abdadmin_staging-------------------------------------------------
--CREATE ROLE abdadmin_staging WITH LOGIN PASSWORD 'Adm1n002Stag!ng';

SELECT current_database();

-- 1. Grant base schema tracking capabilities
GRANT ALL ON SCHEMA public TO abdadmin_staging;

-- 2. Grant rights to all tables currently existing in the database
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO abdadmin_staging;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO abdadmin_staging;

-- 3. 🌟 THE DEFAULT PRIVILEGES INTEGRATION
-- Ensures that if tables are generated by Entity Framework migrations,
-- abdadmin_staging is automatically granted full access rights!
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO abdadmin_staging;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO abdadmin_staging;


