
--  abdadmin_prod-------------------------------------------------
-- CREATE ROLE abdadmin_prod WITH LOGIN PASSWORD 'Adm1n003Pr0d';

SELECT current_database();

-- 1. Grant base schema tracking capabilities
GRANT ALL ON SCHEMA public TO abdadmin_prod;

-- 2. Grant rights to all tables currently existing in the database
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO abdadmin_prod;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO abdadmin_prod;

-- 3. 🌟 THE DEFAULT PRIVILEGES INTEGRATION
-- Ensures that if tables are generated by Entity Framework migrations,
-- abdadmin_prod is automatically granted full access rights!
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO abdadmin_prod;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO abdadmin_prod;

