
--  abdadmin_dev-------------------------------------------------
-- CREATE ROLE abdadmin_dev WITH LOGIN PASSWORD 'Adm1n001D3v';

SELECT current_database();

-- 1. Grant base schema tracking capabilities
GRANT ALL ON SCHEMA public TO abdadmin_dev;

-- 2. Grant rights to all tables currently existing in the database
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO abdadmin_dev;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO abdadmin_dev;

-- 3. 🌟 THE DEFAULT PRIVILEGES INTEGRATION
-- Ensures that if tables are generated by Entity Framework migrations,
-- abdadmin_dev is automatically granted full access rights!
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO abdadmin_dev;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO abdadmin_dev;


